import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:5186');await page.waitForFunction(()=>window.fogbound?.scene?.art);await page.locator('#launch').click();
await page.waitForFunction(()=>window.fogbound.scene.soundFX.buffers.size===32);
await page.evaluate(()=>{const m=window.fogbound.match;m.survivorAI=()=>{};m.killerAI=()=>{};Object.assign(m.player,{x:600,y:650,angle:0});Object.assign(m.killer,{x:750,y:650});const s=m.survivors[1];Object.assign(s,{x:1600,y:1100,life:'hooked',hooks:1});});
await page.mouse.move(1100,450);const before=await page.evaluate(()=>window.fogbound.match.player.x);await page.keyboard.down('KeyA');await page.waitForTimeout(120);await page.keyboard.up('KeyA');assert.ok(await page.evaluate(()=>window.fogbound.match.player.x)<before);assert.ok(Math.abs(await page.evaluate(()=>window.fogbound.match.player.angle))<.1);
await page.waitForTimeout(200);assert.equal(await page.locator('.direction-marker.hook').count(),1);await page.screenshot({path:'artifacts/feedback-survivor.png'});
await page.evaluate(()=>{const m=window.fogbound.match,p=m.player,h=m.survivors[2];p.life='injured';Object.assign(h,{x:p.x+20,y:p.y,action:'heal:'+p.id,progress:.46});});await page.waitForTimeout(150);assert.match(await page.locator('#prompt').innerText(),/46%/);await page.screenshot({path:'artifacts/feedback-healing.png'});
await page.evaluate(()=>{const m=window.fogbound.match;Object.assign(m.player,{x:820,y:670,cooldown:0,transition:0});m.survivors[2].action='';});await page.keyboard.press('Space',{delay:80});await page.waitForTimeout(650);assert.equal(await page.evaluate(()=>window.fogbound.match.player.level),1);await page.screenshot({path:'artifacts/feedback-upstairs.png'});
await page.evaluate(()=>{Object.assign(window.fogbound.match.player,{x:1020,y:690,cooldown:0,transition:0});});await page.keyboard.press('Space',{delay:80});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.fogbound.match.player.level),0);await page.screenshot({path:'artifacts/feedback-drop.png'});await page.waitForTimeout(800);
await page.keyboard.press('Escape');await page.locator('#quit').click();await page.locator('[data-role="killer"]').click();await page.locator('#launch').click();
await page.evaluate(()=>{const m=window.fogbound.match;m.survivorAI=()=>{};m.killerAI=()=>{};Object.assign(m.killer,{x:650,y:650,cooldown:0});m.survivors.forEach((s,i)=>Object.assign(s,{x:1100+i*80,y:850}));});await page.mouse.move(1000,450);await page.mouse.down();await page.waitForTimeout(550);assert.ok(await page.evaluate(()=>window.fogbound.match.killer.charge)>.25);await page.screenshot({path:'artifacts/feedback-charge.png'});await page.mouse.up();await page.waitForTimeout(60);await page.screenshot({path:'artifacts/feedback-swing.png'});assert.ok(await page.evaluate(()=>window.fogbound.match.killer.attackCharge)>.25);
await page.waitForTimeout(1600);await page.evaluate(()=>{const m=window.fogbound.match,h=m.hooks[0];m.carried=0;m.hang(h);Object.assign(m.killer,{x:h.x+65,y:h.y+60});m.survivors[0].hooks=2;});await page.waitForTimeout(100);await page.screenshot({path:'artifacts/feedback-hook.png'});
await page.evaluate(()=>{const m=window.fogbound.match,s=m.survivors[0],r=m.survivors[1];Object.assign(r,{x:s.x+20,y:s.y});m.work(r,{kind:'rescue',target:s,id:s.id,label:''},2.5);});await page.waitForTimeout(150);assert.equal(await page.locator('.direction-marker.rescue').count(),1);await page.screenshot({path:'artifacts/feedback-rescue.png'});
await page.evaluate(()=>{const m=window.fogbound.match,p=m.pallets[0];p.state='down';Object.assign(m.killer,{x:p.x,y:p.y-35,cooldown:0,progress:0});});await page.keyboard.down('KeyE');await page.waitForTimeout(850);assert.match(await page.evaluate(()=>window.fogbound.match.killer.action),/^break:/);await page.screenshot({path:'artifacts/feedback-breaking.png'});await page.waitForTimeout(1600);await page.keyboard.up('KeyE');assert.equal(await page.evaluate(()=>window.fogbound.match.pallets[0].state),'broken');
await page.evaluate(()=>{const m=window.fogbound.match;m.survivors.forEach(s=>s.life='down');});await page.waitForSelector('#again');
console.log({samples:await page.evaluate(()=>window.fogbound.scene.soundFX.buffers.size),errors});await browser.close();assert.deepEqual(errors,[]);


